In [2]:
import pandas as pd

In [3]:
df_customers=pd.read_csv("customers.csv")

In [4]:
df_orders=pd.read_csv("orders.csv")

In [5]:
df_payments=pd.read_csv("payments.csv")

In [6]:
df_products=pd.read_csv("products.csv")

In [7]:
df_orders

,OrderID,CustomerID,OrderDate,ProductID,Quantity,Discount,PaymentMethod,Status
0,500001,103695,2025-08-28,2003,4.0,0.10,Gateway,Completed
1,500002,107935,2024-05-31,2014,1.0,0.10,Wallet,Completed
2,500003,105141,2025-08-10,2002,1.0,0.20,CardToCard,Completed
3,500004,108780,2024-10-11,2012,1.0,0.10,Gateway,Completed
4,500005,101187,2024-02-19,2008,2.0,0.00,Gateway,Completed
...,...,...,...,...,...,...,...,...
50115,546916,106069,2024-11-08,2003,1.0,0.10,CardToCard,Completed
50116,509802,107180,2024-09-19,2012,1.0,0.10,CardToCard,Completed
50117,538801,109723,2025-02-19,2006,2.0,0.05,Wallet,Completed
50118,524670,108719,2025-08-08,2013,1.0,0.05,Gateway,Completed
50119,544234,106789,2024-04-03,2003,1.0,0.00,Gateway,Completed

In [8]:
df_orders.isnull().sum()

OrderID            0
CustomerID         0
OrderDate         35
ProductID          0
Quantity          80
Discount         221
PaymentMethod    452
Status             0
dtype: int64

In [9]:
#percenatge of missing values in each columns
missing_pct = df_orders.isnull().mean() * 100
missing_pct[missing_pct > 0].sort_values(ascending=False)

PaymentMethod    0.901836
Discount         0.440942
Quantity         0.159617
OrderDate        0.069832
dtype: float64

In [10]:
df_customers.isnull().sum()

CustomerID           0
Age                180
City               119
SignupDate           0
CustomerSegment      0
dtype: int64

In [11]:
#customer k table mai kitne column mai kitne percentage value missing hain
df_customers.isnull().mean()*100

CustomerID         0.00
Age                1.80
City               1.19
SignupDate         0.00
CustomerSegment    0.00
dtype: float64

In [12]:
df_customers[['Age','City']].isnull().mean()*100

Age     1.80
City    1.19
dtype: float64

In [13]:
missing_pct=df_customers.isnull().mean()*100
missing_pct[missing_pct>0]

Age     1.80
City    1.19
dtype: float64

In [14]:
df_payments.isnull().sum()

PaymentID         0
OrderID           0
PaymentDate      35
PaymentStatus     0
dtype: int64

In [15]:
missing_pct=df_payments.isnull().mean()*100
missing_pct[missing_pct>0]

PaymentDate    0.07
dtype: float64

In [16]:
df_products.isnull().sum()

ProductID      0
ProductName    0
Category       0
UnitPrice      0
dtype: int64

In [17]:
#checking for outliers

In [18]:
df_orders.describe()

             OrderID     CustomerID     ProductID      Quantity      Discount
count   50120.000000   50120.000000  50120.000000  50040.000000  49899.000000
mean   525003.244872  105543.821788   2009.458799      1.881455      0.075130
std     14433.904231   22079.891005      5.577743      1.078846      0.077492
min    500001.000000  100001.000000   2001.000000     -2.000000      0.000000
25%    512503.750000  102515.000000   2004.000000      1.000000      0.000000
50%    525006.500000  105017.000000   2008.000000      2.000000      0.050000
75%    537501.250000  107510.000000   2014.000000      2.000000      0.100000
max    550000.000000  999999.000000   2020.000000      5.000000      0.300000

In [19]:
df_customers.describe()

         CustomerID          Age
count   10000.00000  9820.000000
mean   105000.50000    41.321487
std      2886.89568    13.802441
min    100001.00000    18.000000
25%    102500.75000    29.000000
50%    105000.50000    41.000000
75%    107500.25000    53.000000
max    110000.00000    65.000000

In [20]:
df_payments.describe()

           PaymentID        OrderID
count   50000.000000   50000.000000
mean   825000.500000  525000.500000
std     14433.901067   14433.901067
min    800001.000000  500001.000000
25%    812500.750000  512500.750000
50%    825000.500000  525000.500000
75%    837500.250000  537500.250000
max    850000.000000  550000.000000

In [21]:
df_products.describe()

        ProductID   UnitPrice
count    20.00000   20.000000
mean   2010.50000   61.400000
std       5.91608   62.836798
min    2001.00000    7.000000
25%    2005.75000   20.250000
50%    2010.50000   45.000000
75%    2015.25000   69.750000
max    2020.00000  260.000000

In [22]:
#data cleaning for order table

In [23]:
df_orders.isnull().mean()*100

OrderID          0.000000
CustomerID       0.000000
OrderDate        0.069832
ProductID        0.000000
Quantity         0.159617
Discount         0.440942
PaymentMethod    0.901836
Status           0.000000
dtype: float64

In [24]:
#dropping orderdate column
df_orders=df_orders.drop(columns=['OrderDate'])

In [25]:
df_orders.isnull().mean()*100

OrderID          0.000000
CustomerID       0.000000
ProductID        0.000000
Quantity         0.159617
Discount         0.440942
PaymentMethod    0.901836
Status           0.000000
dtype: float64

In [26]:
#claculating median for quantity column
median=df_orders['Quantity'].median()
median

np.float64(2.0)

In [27]:
#filling with median in missing value in quantity column
df_orders['Quantity']=df_orders['Quantity'].fillna(median)


df_orders['Quantity']

0        4.0
1        1.0
2        1.0
3        1.0
4        2.0
        ...
50115    1.0
50116    1.0
50117    2.0
50118    1.0
50119    1.0
Name: Quantity, Length: 50120, dtype: float64

In [28]:
df_orders.isnull().mean()*100

OrderID          0.000000
CustomerID       0.000000
ProductID        0.000000
Quantity         0.000000
Discount         0.440942
PaymentMethod    0.901836
Status           0.000000
dtype: float64

In [29]:
df_orders.dtypes

OrderID            int64
CustomerID         int64
ProductID          int64
Quantity         float64
Discount         float64
PaymentMethod        str
Status               str
dtype: object

In [30]:
df_orders.isnull().mean()*100

OrderID          0.000000
CustomerID       0.000000
ProductID        0.000000
Quantity         0.000000
Discount         0.440942
PaymentMethod    0.901836
Status           0.000000
dtype: float64

In [31]:
#calculating median for discount coolumn
discount_median=df_orders['Discount'].median()
discount_median

np.float64(0.05)

In [32]:
#filling median in missing cells of discount column
df_orders['Discount']=df_orders['Discount'].fillna(discount_median)
df_orders['Discount']

0        0.10
1        0.10
2        0.20
3        0.10
4        0.00
         ...
50115    0.10
50116    0.10
50117    0.05
50118    0.05
50119    0.00
Name: Discount, Length: 50120, dtype: float64

In [33]:
df_orders.isnull().mean()*100

OrderID          0.000000
CustomerID       0.000000
ProductID        0.000000
Quantity         0.000000
Discount         0.000000
PaymentMethod    0.901836
Status           0.000000
dtype: float64

In [34]:
#filling unknown in missing cell of payment method
df_orders['PaymentMethod']=df_orders['PaymentMethod'].fillna('unknown')

In [35]:
df_orders['PaymentMethod']

0           Gateway
1            Wallet
2        CardToCard
3           Gateway
4           Gateway
            ...
50115    CardToCard
50116    CardToCard
50117        Wallet
50118       Gateway
50119       Gateway
Name: PaymentMethod, Length: 50120, dtype: str

In [36]:
df_orders.isnull().mean()*100

OrderID          0.0
CustomerID       0.0
ProductID        0.0
Quantity         0.0
Discount         0.0
PaymentMethod    0.0
Status           0.0
dtype: float64

In [37]:
#checking for duplicates
df_orders.duplicated().sum()

np.int64(120)

In [38]:
#dropping dupliates
df_orders.drop_duplicates()

,OrderID,CustomerID,ProductID,Quantity,Discount,PaymentMethod,Status
0,500001,103695,2003,4.0,0.10,Gateway,Completed
1,500002,107935,2014,1.0,0.10,Wallet,Completed
2,500003,105141,2002,1.0,0.20,CardToCard,Completed
3,500004,108780,2012,1.0,0.10,Gateway,Completed
4,500005,101187,2008,2.0,0.00,Gateway,Completed
...,...,...,...,...,...,...,...
49995,549996,104649,2013,2.0,0.05,CardToCard,Completed
49996,549997,108686,2004,1.0,0.10,Gateway,Completed
49997,549998,107639,2010,1.0,0.00,Cash,Completed
49998,549999,108215,2005,1.0,0.00,CardToCard,Completed
49999,550000,102166,2004,1.0,0.10,Wallet,Completed

In [39]:
df_orders.dtypes

OrderID            int64
CustomerID         int64
ProductID          int64
Quantity         float64
Discount         float64
PaymentMethod        str
Status               str
dtype: object

In [40]:
#checking duplicated in customer tabe
df_customers.duplicated().sum()

np.int64(0)

In [41]:
#checking missing values in customer table
df_customers.isnull().sum()

CustomerID           0
Age                180
City               119
SignupDate           0
CustomerSegment      0
dtype: int64

In [42]:
df_customers.isnull().mean()*100

CustomerID         0.00
Age                1.80
City               1.19
SignupDate         0.00
CustomerSegment    0.00
dtype: float64

In [43]:
df_customers.describe()

         CustomerID          Age
count   10000.00000  9820.000000
mean   105000.50000    41.321487
std      2886.89568    13.802441
min    100001.00000    18.000000
25%    102500.75000    29.000000
50%    105000.50000    41.000000
75%    107500.25000    53.000000
max    110000.00000    65.000000

In [44]:
df_customers['Age'].max()                 # directly from the column

np.float64(65.0)

In [45]:
q3= df_customers['Age'].quantile(0.75)
q1= df_customers['Age'].quantile(0.25)
iqr=q3-q1
iqr

np.float64(24.0)

In [46]:
ul=q3+(1.5*iqr)
ll=q1-(1.5*iqr)

print(ul)

print(ll)

89.0
-7.0

In [47]:
#we gonna fill the missing value with mean
df_customers['Age'].fillna(df_customers['Age'].mean())

0       22.0
1       55.0
2       49.0
3       39.0
4       38.0
        ...
9995    40.0
9996    65.0
9997    34.0
9998    45.0
9999    47.0
Name: Age, Length: 10000, dtype: float64

In [48]:
#finding duplicates in producgt table\
df_products.duplicated().sum()

np.int64(0)

In [49]:
#finding missing values in product table
df_products.isnull().mean()*100

ProductID      0.0
ProductName    0.0
Category       0.0
UnitPrice      0.0
dtype: float64

In [50]:
df_products.dtypes

ProductID        int64
ProductName        str
Category           str
UnitPrice      float64
dtype: object

In [51]:
#finding duplicates in payment table
df_payments.duplicated().sum()

np.int64(0)

In [52]:
#finding missing values in payment table
df_payments.isnull().mean()*100

PaymentID        0.00
OrderID          0.00
PaymentDate      0.07
PaymentStatus    0.00
dtype: float64

In [53]:
df_payments = df_payments.dropna(subset=['PaymentDate'])

In [54]:
df_payments.isnull().mean()*100

PaymentID        0.0
OrderID          0.0
PaymentDate      0.0
PaymentStatus    0.0
dtype: float64

In [55]:
df_final=pd.read_csv("clean_final_data.csv")

In [56]:
df_final

,OrderID,CustomerID,OrderDate,ProductID,Quantity,Discount,PaymentMethod,Status,Age,City,SignupDate,CustomerSegment,ProductName,Category,UnitPrice,Sales,OrderValue
0,500001,103695,2025-08-28,2003,4.0,10.0,Gateway,Completed,36.0,Qom,2024-03-05,Regular,USB-C Cable,Accessories,9.0,32.0,32.0
1,500002,107935,2024-05-31,2014,1.0,10.0,Wallet,Completed,49.0,Kerman,2025-06-04,Regular,Backpack,Accessories,42.0,38.0,38.0
2,500003,105141,2025-08-10,2002,1.0,20.0,CardToCard,Completed,36.0,Tehran,2025-10-19,Regular,Mechanical Keyboard,Electronics,62.0,50.0,50.0
3,500004,108780,2024-10-11,2012,1.0,10.0,Gateway,Completed,45.0,Shiraz,2023-12-07,Regular,Office Chair,Home Office,180.0,162.0,162.0
4,500005,101187,2024-02-19,2008,2.0,0.0,Gateway,Completed,24.0,Karaj,2023-12-02,Regular,Phone Case,Accessories,14.0,28.0,28.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49217,549996,104649,2025-04-30,2013,2.0,5.0,CardToCard,Completed,32.0,Tehran,2025-03-24,Regular,Notebook,Stationery,7.0,13.0,13.0
49218,549997,108686,2025-01-26,2004,1.0,10.0,Gateway,Completed,45.0,Tehran,2024-03-08,New,Power Bank,Electronics,35.0,32.0,32.0
49219,549998,107639,2026-04-13,2010,1.0,0.0,Cash,Completed,56.0,Shiraz,2025-02-19,Regular,Fitness Band,Wearables,55.0,55.0,55.0
49220,549999,108215,2025-04-18,2005,1.0,0.0,CardToCard,Completed,20.0,Qom,2025-08-11,Regular,Laptop Stand,Accessories,28.0,28.0,28.0
49221,550000,102166,2024-04-06,2004,1.0,10.0,Wallet,Completed,62.0,Isfahan,2025-02-01,New,Power Bank,Electronics,35.0,32.0,32.0

In [57]:
df_customers

      CustomerID   Age     City  SignupDate CustomerSegment
0         100001  22.0   Tehran  2023-09-11         Regular
1         100002  55.0   Tabriz  2024-01-16             VIP
2         100003  49.0    Karaj  2025-07-31             New
3         100004  39.0   Tehran  2023-04-23             New
4         100005  38.0   Tehran  2023-04-29         Regular
...          ...   ...      ...         ...             ...
9995      109996  40.0    Ahvaz  2025-07-16         Regular
9996      109997  65.0   Shiraz  2023-09-20         Regular
9997      109998  34.0   Tehran  2025-01-04         Regular
9998      109999  45.0  Mashhad  2023-02-13             VIP
9999      110000  47.0    Ahvaz  2023-06-04             New

[10000 rows x 5 columns]

In [58]:
df_payments

       PaymentID  OrderID PaymentDate PaymentStatus
0         800001   500001  2025-08-28          Paid
1         800002   500002  2024-05-31          Paid
2         800003   500003  2025-08-10          Paid
3         800004   500004  2024-10-11          Paid
4         800005   500005  2024-02-19          Paid
...          ...      ...         ...           ...
49995     849996   549996  2025-04-30          Paid
49996     849997   549997  2025-01-26          Paid
49997     849998   549998  2026-04-13          Paid
49998     849999   549999  2025-04-18          Paid
49999     850000   550000  2024-04-06          Paid

[49965 rows x 4 columns]

In [59]:
df_products

    ProductID          ProductName     Category  UnitPrice
0        2001       Wireless Mouse  Electronics       18.0
1        2002  Mechanical Keyboard  Electronics       62.0
2        2003          USB-C Cable  Accessories        9.0
3        2004           Power Bank  Electronics       35.0
4        2005         Laptop Stand  Accessories       28.0
5        2006               Webcam  Electronics       48.0
6        2007           Headphones  Electronics       75.0
7        2008           Phone Case  Accessories       14.0
8        2009          Smart Watch    Wearables      120.0
9        2010         Fitness Band    Wearables       55.0
10       2011            Desk Lamp  Home Office       32.0
11       2012         Office Chair  Home Office      180.0
12       2013             Notebook   Stationery        7.0
13       2014             Backpack  Accessories       42.0
14       2015    Bluetooth Speaker  Electronics       58.0
15       2016              Monitor  Electronics       21.0
16       2017           HDMI Cable  Accessories       11.0
17       2018           Microphone  Electronics       85.0
18       2019               Tablet  Electronics      260.0
19       2020    Gaming Controller       Gaming       68.0

In [62]:
df_clean_merged = (
    df_orders
    .merge(df_customers, on='CustomerID', how='left')
    .merge(df_products, on='ProductID', how='left')
    .merge(df_payments, on='OrderID', how='left')
)

In [63]:
df_clean_merged

,OrderID,CustomerID,ProductID,Quantity,Discount,PaymentMethod,Status,Age,City,SignupDate,CustomerSegment,ProductName,Category,UnitPrice,PaymentID,PaymentDate,PaymentStatus
0,500001,103695,2003,4.0,0.10,Gateway,Completed,36.0,Qom,2024-03-05,Regular,USB-C Cable,Accessories,9.0,800001.0,2025-08-28,Paid
1,500002,107935,2014,1.0,0.10,Wallet,Completed,49.0,Kerman,2025-06-04,Regular,Backpack,Accessories,42.0,800002.0,2024-05-31,Paid
2,500003,105141,2002,1.0,0.20,CardToCard,Completed,36.0,Tehran,2025-10-19,Regular,Mechanical Keyboard,Electronics,62.0,800003.0,2025-08-10,Paid
3,500004,108780,2012,1.0,0.10,Gateway,Completed,45.0,Shiraz,2023-12-07,Regular,Office Chair,Home Office,180.0,800004.0,2024-10-11,Paid
4,500005,101187,2008,2.0,0.00,Gateway,Completed,24.0,Karaj,2023-12-02,Regular,Phone Case,Accessories,14.0,800005.0,2024-02-19,Paid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50115,546916,106069,2003,1.0,0.10,CardToCard,Completed,25.0,Isfahan,2024-05-15,New,USB-C Cable,Accessories,9.0,846916.0,2024-11-08,Paid
50116,509802,107180,2012,1.0,0.10,CardToCard,Completed,32.0,tehran,2023-01-06,Regular,Office Chair,Home Office,180.0,809802.0,2024-09-19,Paid
50117,538801,109723,2006,2.0,0.05,Wallet,Completed,23.0,Karaj,2023-10-20,New,Webcam,Electronics,48.0,838801.0,2025-02-19,Paid
50118,524670,108719,2013,1.0,0.05,Gateway,Completed,48.0,Tabriz,2023-09-09,Regular,Notebook,Stationery,7.0,824670.0,2025-08-08,Paid
50119,544234,106789,2003,1.0,0.00,Gateway,Completed,29.0,Karaj,2025-05-06,New,USB-C Cable,Accessories,9.0,844234.0,2024-04-03,Paid